# FROM mcr.microsoft.com/windows/server:ltsc2022
# FROM mcr.microsoft.com/windows/nanoserver:ltsc2022 <- Lightest, but no powershell
# FROM mcr.microsoft.com/windows/nanoserver:ltsc2022 <- Medium, with powershell
FROM mcr.microsoft.com/windows/servercore:ltsc2019
USER ContainerAdministrator
RUN cd C:
RUN setx /M PATH "%PATH%;C:/"
COPY ./bins/client.exe ./
COPY ./bins/server.exe ./
EXPOSE 4444
EXPOSE 4445
# ENTRYPOINT ["server.exe", "-p", "4444", "-pr", "All"]