apiVersion: v1
kind: Service
metadata:
  labels:
    app: tcp-server
  name: tcp-server
  namespace: demo
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app: tcp-server
  sessionAffinity: None
  type: ClusterIP
  ports:
  - name: tcp
    port: 4444
    protocol: TCP
    targetPort: 4444
  - name: udp
    port: 4445
    protocol: UDP
    targetPort: 4445
