apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  labels:
    app: tcp-server
  name: tcp-server
  namespace: demo
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tcp-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tcp-server
    spec:
      terminationGracePeriodSeconds: 1000
      containers:
      - image: princepereira/tcp-client-server:test
        command: ["server.exe", "-p", "4444", "-pr", "All", "-pw", "25"]
        imagePullPolicy: Always
        name: tcpudpserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        lifecycle:
          preStop:
            exec:
              command: ["curl", "--connect-timeout", "100", "--max-time", "100", "http://127.0.0.1:8090/kill", "-v"]
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30